### ISSUE TITLE
Prototüüp

### ISSUE THREAD

**Issue by Mirember** [Catsaurus/toDo#2]
https://courses.cs.ut.ee/2017/vl/spring/Main/Protot%C3%BC%C3%BCp

**Comment by rianarandoja** [comment]
![16788281_1318264071554431_1595790765_n](https://cloud.githubusercontent.com/assets/9558476/23198773/9ccc2c5c-f8d2-11e6-8d59-8b6973dfc33e.png)
![16790508_1318264068221098_1486714150_n](https://cloud.githubusercontent.com/assets/9558476/23198775/9ccdb702-f8d2-11e6-8d89-7a30b3b8a762.png)
![16923585_1322903087757196_1837255293_n](https://cloud.githubusercontent.com/assets/9558476/23198774/9cccb0dc-f8d2-11e6-9e51-9f5136156ea0.png)
![abo](https://cloud.githubusercontent.com/assets/9558476/23198777/9ccdebfa-f8d2-11e6-876f-a3c48acb4e3c.PNG)
![add](https://cloud.githubusercontent.com/assets/9558476/23198778/9cd24268-f8d2-11e6-80bb-6e26d67ccc12.PNG)
![pets](https://cloud.githubusercontent.com/assets/9558476/23198776/9ccdd372-f8d2-11e6-97bd-7410688706e6.PNG)
![reg](https://cloud.githubusercontent.com/assets/9558476/23198779/9ce8e28e-f8d2-11e6-9e5e-1daa82b669b7.PNG)
![set](https://cloud.githubusercontent.com/assets/9558476/23198780/9ceab6fe-f8d2-11e6-9241-f5a7d243491d.PNG)
