### ISSUE TITLE
check session in every place where data is altered

### ISSUE THREAD

**Issue by Mirember** [Catsaurus/toDo#43]
kõik taskide lisamised, tehtuks märkimised jmt - seal peab lisama kontrolli, et muudetav asi on ikka sisse loginud kasutaja oma. Muidu saab häkkida.

**Comment by Mirember** [comment]
Delete task jaoks on tehtud

**Comment by rianarandoja** [comment]
sa mõtled protseduuridesse lisaparameetri lisamist või mis?

**Comment by Mirember** [comment]
Ei, mõtlen koodis kontrollida igaks juhuks, kas muudetav task kuulub ikka sisse loginud kasutajale

**Comment by rianarandoja** [comment]
kuhu sa selle kontrolli delete task'i jaoks panid?

**Comment by rianarandoja** [comment]
me võtame kogu aeg id ju sessioni alt

**Comment by Mirember** [comment]
Mõtlesingi, et võrrelda, kas andmebaasist küsitud task kuulub sessioni id kasutaja alla. Kuna muidu saab sessioni kasutaja teha äkki päringut teise id alt (mingi häkiga). Või äkki on mõnes kohas koodis veel küsitud kuidagi mitte sessioni alt taski
